swagger: "2.0"
info:
  title: "Api for Invetto.id"
  description: "API documentation for Invetto.id"
  version: "1.0"
tags:
  - name: bride
    description: "Bride related operations"
schemes:
  - http
basePath: /
